#!/bin/sh

COOKIE_PATH=".cookie"

day=$(date +%d)
year=$(date +%Y)
month=$(date +%m)

if [ $# -gt 0 ]; then
  day=$1
fi

URL="https://adventofcode.com/$year/day/$day/input"

# if [ month ~= "12" ]; then
#   echo "Not December"
#   exit 1
# fi

if [ ! -f "$COOKIE_PATH" ]; then
  echo "Cookie file \"$COOKIE_PATH\" does not exist."
fi

curl --cookie "$COOKIE_PATH" --output "./Inputs/Day$day.txt" "$URL"
